apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: node-server
        image: samuel1797/test-github-actions:0.0.1-e9042f8
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: node-server-service
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3000
