name: CD on Digital Ocean provider

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configuring node (version 12)
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # - name: Running test's application
      # run: npm test (Not implemented yet)

      - name: Set up QEMU (processor emulator)
        uses: docker/setup-qemu-action@v1

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1  

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Bump version and push tag
        id: tagging
        uses: mathieudutour/github-tag-action@v4.5
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64, linux/386
          tags: samuel1797/test-github-actions:${{ steps.tagging.outputs.new_version }}